Naive Bayes is a machine learning classification algorithm that predicts the category of a data point using probability. It assumes that all features are independent of each other. Naive Bayes performs well in many real-world applications such as spam filtering, document categorisation and sentiment analysis.

It is named as "Naive" because it assumes the presence of one feature does not affect other features. 
The "Bayes" part of the name refers to its basis in Bayes’ Theorem.

Types of Naive Bayes Model

1. Gaussian Naive Bayes
2. Multinomial Naive Bayes
3. Bernoulli Naive Bayes

Advantages

In [1]:
# Easy to implement and computationally efficient.
# Effective in cases with a large number of features.
# Performs well even with limited training data.
# It performs well in the presence of categorical features.
# For numerical features data is assumed to come from normal distributions

In [2]:
# disadvantage

In [3]:
# Assumes that features are independent, 
# which may not always hold in real-world data.
# Can be influenced by irrelevant attributes.
# May assign zero probability to unseen events, 
# leading to poor generalization.

1. Import pandas and NumPy

In [4]:
import pandas as pd
import numpy as np

2. Load the dataset

In [45]:
df = pd.read_csv("Loan_default.csv")
print(df)

            LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0       I38PQUQS96   56   85994       50587          520              80
1       HPSK72WA7R   69   50432      124440          458              15
2       C1OZ6DPJ8Y   46   84208      129188          451              26
3       V2KKSFM3UN   32   31713       44799          743               0
4       EY08JDHTZP   60   20437        9139          633               8
...            ...  ...     ...         ...          ...             ...
255342  8C6S86ESGC   19   37979      210682          541             109
255343  98R4KDHNND   32   51953      189899          511              14
255344  XQK1UUUNGP   56   84820      208294          597              70
255345  JAO28CPL4H   42   85109       60575          809              40
255346  ZTH91CGL0B   62   22418       18481          636             113

        NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0                    4         15.23        36      0.44   Bachelor's
1                    1          4.81        60      0.68     Master's
2                    3         21.17        24      0.31     Master's
3                    3          7.07        24      0.23  High School
4                    4          6.51        48      0.73   Bachelor's
...                ...           ...       ...       ...          ...
255342               4         14.11        12      0.85   Bachelor's
255343               2         11.55        24      0.21  High School
255344               3          5.29        60      0.50  High School
255345               1         20.90        48      0.44  High School
255346               2          6.73        12      0.48   Bachelor's

       EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0           Full-time      Divorced         Yes           Yes       Other
1           Full-time       Married          No            No       Other
2          Unemployed      Divorced         Yes           Yes        Auto
3           Full-time       Married          No            No    Business
4          Unemployed      Divorced          No           Yes        Auto
...               ...           ...         ...           ...         ...
255342      Full-time       Married          No            No       Other
255343      Part-time      Divorced          No            No        Home
255344  Self-employed       Married         Yes           Yes        Auto
255345      Part-time        Single         Yes           Yes       Other
255346     Unemployed      Divorced         Yes            No   Education

       HasCoSigner  Default
0              Yes        0
1              Yes        0
2               No        1
3               No        0
4               No        0
...            ...      ...
255342          No        0
255343          No        1
255344         Yes        0
255345          No        0
255346         Yes        0

[255347 rows x 18 columns]

3. Understand the dataset

In [ ]:
# checked the dataset using
# df.head()
# df.shape
# df.info() 
# df.describe()
# df.isnull().sum()

In [ ]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [16]:
df.dtypes
# int64 → integer/numerical data
# float64 → decimal/numerical data
# object → usually text/categorical data
# bool → True/False

LoanID                str
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education             str
EmploymentType        str
MaritalStatus         str
HasMortgage           str
HasDependents         str
LoanPurpose           str
HasCoSigner           str
Default             int64
dtype: object

In [ ]:
df.shape

(255347, 18)

In [12]:
df.info() 
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  str
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  str
 11  EmploymentType  255347 non-null  str
 12  MaritalStatus   255347 non-null  str
 13  HasMortgage     255347 non-null  str
 14  HasDependents   255347 non-null  str
 15  LoanPurpose     255347 non-null  str
 16  HasCoSigner     255347 non-null  str
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(8), str(8)
memory usage: 35.1 MB

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [13]:
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

4. Check the target variable

In [14]:
print(df["Default"].value_counts())

Default
0    225694
1     29653
Name: count, dtype: int64

In [15]:
print(df["Default"].value_counts(normalize=True) * 100)

Default
0    88.387175
1    11.612825
Name: proportion, dtype: float64

5. Create X

In [17]:
# features selections

In [ ]:
X = df.drop(["Default", "LoanID"], axis=1) # input

6. Create y

In [ ]:
y=df["Default"] # target values

In [20]:
print(X.shape)
print(y.shape)

(255347, 16)
(255347,)

In [22]:
print(X.head())
print(y.head())

   Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56   85994       50587          520              80               4
1   69   50432      124440          458              15               1
2   46   84208      129188          451              26               3
3   32   31713       44799          743               0               3
4   60   20437        9139          633               8               4

   InterestRate  LoanTerm  DTIRatio    Education EmploymentType MaritalStatus  \
0         15.23        36      0.44   Bachelor's      Full-time      Divorced
1          4.81        60      0.68     Master's      Full-time       Married
2         21.17        24      0.31     Master's     Unemployed      Divorced
3          7.07        24      0.23  High School      Full-time       Married
4          6.51        48      0.73   Bachelor's     Unemployed      Divorced

  HasMortgage HasDependents LoanPurpose HasCoSigner
0         Yes           Yes       Other         Yes
1          No            No       Other         Yes
2         Yes           Yes        Auto          No
3          No            No    Business          No
4          No           Yes        Auto          No
0    0
1    0
2    1
3    0
4    0
Name: Default, dtype: int64

7. Separate numerical and categorical columns

In [ ]:
# seprating a column between two part numerical and categorical
#because model does not understand a textdata /categorical data it only understand a numerical data

In [23]:
numerical_cols = X.select_dtypes(include="number").columns

print("Numerical columns:")
print(numerical_cols)

Numerical columns:
Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio'],
      dtype='str')

In [24]:
categorical_cols = X.select_dtypes(include="str").columns
print("Categorical columns:")
print(categorical_cols)

Categorical columns:
Index(['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
       'HasDependents', 'LoanPurpose', 'HasCoSigner'],
      dtype='str')

8. Create the preprocessor

In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

9. Combine the preprocessing

In [47]:


preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", StandardScaler(), numerical_cols),
        ("categorical", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ]
)

10. Split the data

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,y, 
    test_size=0.2 , 
    random_state=42,
    stratify=y 
)

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(204277, 16)
(51070, 16)
(204277,)
(51070,)

In [ ]:
# Because  dataset contains both numerical and 
# categorical features, and i already created a ColumnTransformer, 
# can combine preprocessing with Gaussian Naive Bayes.

11. Import Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

12. Create the model

In [ ]:
model = GaussianNB()

13. Process training data

In [33]:
X_train_processed = preprocessor.fit_transform(X_train)

14. Process test data

In [ ]:
# scale your numerical columns
# one-hot encode your categorical columns
# learn the preprocessing only from the training data

In [34]:
X_test_processed = preprocessor.transform(X_test)

15. Train the Naive Bayes model

In [35]:
model.fit(X_train_processed, y_train)

GaussianNB()

16. Make predictions

In [ ]:
# Now the trained Naive Bayes model will predict 
# the Default values for the test data.

In [36]:
y_pred = model.predict(X_test_processed)

In [37]:
print(y_pred[:10])

[0 0 0 0 0 0 0 0 0 0]

17. Check accuracy

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8847464264734678

18. Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[44886   253]
 [ 5633   298]]

19. Classification report

In [41]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.99      0.94     45139
           1       0.54      0.05      0.09      5931

    accuracy                           0.88     51070
   macro avg       0.71      0.52      0.52     51070
weighted avg       0.85      0.88      0.84     51070

20. Prediction probabilities

In [42]:
y_prob = model.predict_proba(X_test_processed)

print(y_prob[:10])

[[0.97655193 0.02344807]
 [0.98408091 0.01591909]
 [0.92197506 0.07802494]
 [0.81971651 0.18028349]
 [0.94243804 0.05756196]
 [0.99202781 0.00797219]
 [0.73694716 0.26305284]
 [0.89404276 0.10595724]
 [0.6325561  0.3674439 ]
 [0.84607001 0.15392999]]

21. ROC-AUC

In [48]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob[:, 1])

print("ROC-AUC Score:", auc)

ROC-AUC Score: 0.7455478806917581